name: Continuous Deployment

on:
  push:
    branches: [ production ]

env:
  IN_PRODUCTION: false
  BASE_URL: https://loopbin.dev
  GOOGLE_ANALYTICS_ID: ${{ secrets.GOOGLE_ANALYTICS_ID }}

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn generate
      - uses: w9jds/firebase-action@master
        with:
          args: deploy -P default --only hosting:loopbin
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
