name: Continuous Integration

on:
  push:
    branches: [main]

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: yarn install
      - run: yarn generate
      - uses: w9jds/firebase-action@master
        with:
          args: deploy -P vivid --only hosting:loopbin-vivid
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
